site_name: Bitlayer Docs
site_url: https://bitlayer-org.github.io/docs
site_author: bitlayer
repo_url: https://github.com/bitlayer-org/docs
docs_dir: docs/
theme:
    name: material
    favicon: images/bitlayer-logo.jpg
    logo: images/bitlayer-logo.jpg
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
        - javascript
        - shell
nav:
    - About: index.md
    - Quick Start: quick-start.md
    - Use: 
      - Testnet: use/testnet.md
    - Build:
      - Compile and Run: build/dev/install.md
      - Deployment: build/dev/deploy.md
      - JSON RPC: build/dev/json-rpc.md
      - Testnet: build/dev/testnet.md
    - Learn:
      - learn/roadmap.md
      - learn/bitvm.md

